"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, MapPin, Phone, Menu, X, MessageCircle, Instagram, Facebook, ChevronDown } from "lucide-react";
const nav = [["Home","/"],["Products","/products"],["Brands","/brands"],["Offers & EMI","/offers"],["About","/about"],["Contact","/contact"]];
export function SiteHeader() {
  const [open,setOpen]=useState(false);
  return <header className="header"><div className="nav wrap"><Link href="/" className="brand" aria-label="SR Associates home"><span className="brand-mark">SR<span>.</span></span><span className="brand-name">ASSOCIATES<small>POLLACHI · SINCE 2001</small></span></Link><nav className="desktop-nav">{nav.map(([n,h])=><Link href={h} key={h}>{n}</Link>)}</nav><Link href="/contact" className="nav-cta">Visit our store <ArrowRight size={15}/></Link><button className="menu-toggle" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile-nav">{nav.map(([n,h])=><Link href={h} key={h} onClick={()=>setOpen(false)}>{n}<ArrowRight size={16}/></Link>)}<a href="https://maps.google.com/?q=SR+Associates+Pollachi">Get directions <MapPin size={16}/></a></div>}</header>
}
export function SiteFooter(){return <footer className="footer"><div className="wrap footer-main"><div className="footer-brand"><Link href="/" className="brand"><span className="brand-mark">SR<span>.</span></span><span className="brand-name">ASSOCIATES<small>POLLACHI · SINCE 2001</small></span></Link><p>Good things for the place you call home.</p><p className="footer-address">Pollachi, Tamil Nadu</p></div><div><h4>Explore</h4>{nav.slice(1,5).map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><h4>Contact our team</h4><a href="/contact">Call details to be added</a><a href="/contact">WhatsApp details to be added</a><Link href="/contact">Plan a visit</Link><span className="hours">Hours to be confirmed</span></div><div><h4>Come say hello</h4><a href="https://maps.google.com/?q=SR+Associates+Pollachi">Pollachi, Tamil Nadu</a><div className="social"><a aria-label="Instagram" href="#"><Instagram size={17}/></a><a aria-label="Facebook" href="#"><Facebook size={17}/></a></div></div></div><div className="wrap footer-bottom"><span>© 2026 SR Associates. Made for home, in Pollachi.</span><span>Privacy · Terms</span></div></footer>}
export function FloatingActions(){return <div className="float-actions"><a href="/contact" aria-label="Call SR Associates"><Phone size={19}/></a><a href="/contact" aria-label="WhatsApp SR Associates"><MessageCircle size={19}/></a></div>}
export function FAQ(){const [active,setActive]=useState<number|null>(0);const qs=["Can I visit the showroom without an appointment?","Do you offer delivery in Pollachi and nearby areas?","Which EMI options are available?","Can I exchange my old appliance?","Do you help with installation?","Are the products covered by a manufacturer warranty?","Can I check product availability before visiting?","Do you sell furniture as well as appliances?","What are your showroom opening hours?","How can I reach the showroom?"];return <div className="faq-list">{qs.map((q,i)=><div className={`faq-item ${active===i?"active":""}`} key={q}><button onClick={()=>setActive(active===i?null:i)} aria-expanded={active===i}>{q}<ChevronDown size={18}/></button>{active===i&&<p>Absolutely. Our team at SR Associates is happy to help. Contact us and we’ll share the latest details before your visit.</p>}</div>)}</div>}
